upstream node_apis {
    server api:3000;   # Docker DNS automatically load-balances scaled containers
}

server {
    listen 80;

    location / {
        proxy_pass http://node_apis;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
